version: "3.8"
services:
    database:
        container_name: liliya-pg
        image: postgres:13
        restart: unless-stopped        
        environment:
            POSTGRES_USER: main
            POSTGRES_PASSWORD: main
            POSTGRES_DB: main
        ports:
            - 55555:5432
        networks:
            - internal
            - external

    app:
        container_name: liliya-app
        build: docker/app
        restart: unless-stopped
        volumes:
            - ./phpconfig:/usr/local/etc/php
            - ./www-html:/var/www/html
        depends_on:
            - database
        ports: 
            - 9000:9000
            - 9998:9998
        networks:
            - internal

    webserver:
        container_name: liliya-nginx
        image: nginx:latest
        depends_on:
            - app
        restart: unless-stopped
        ports:
            - 8888:80
        volumes:
            - ./www-html:/var/www/html
            - ./nginx-conf:/etc/nginx/conf.d
        networks:
            - external
            - internal

networks:
    external:
        driver: bridge
    internal:
        driver: bridge      